### ISSUE TITLE
Wrong keywords in forwardingList

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ExecutionAndTraceLog#221]
I noticed that in the forwarding list there are keywords "server-name" and "service-name".
In the template from the ApplicationPattern I only see "server-name", so I guess this might be wrong as I would expect this should be "server-name" everywhere...

Example:
```
  - forwarding-name: ServiceRequestCausesLoggingRequest
    uuid: eatl-2-0-1-op-fc-bm-002
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/redirect-service-request-information
          uuid: eatl-2-0-1-op-s-bm-002
      fc-port-update:
        - server-name: /v1/redirect-service-request-information
          uuid: eatl-2-0-1-op-s-bm-002
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/register-yourself
        uuid: eatl-2-0-1-op-s-bm-000
      - server-name: /v1/embed-yourself
        uuid: eatl-2-0-1-op-s-bm-001
      - server-name: /v1/redirect-service-request-information
        uuid: eatl-2-0-1-op-s-bm-002
      - server-name: /v1/redirect-oam-request-information
        uuid: eatl-2-0-1-op-s-bm-003
      - server-name: /v1/end-subscription
        uuid: eatl-2-0-1-op-s-bm-004
      - server-name: /v1/inquire-oam-request-approvals
        uuid: eatl-2-0-1-op-s-bm-005
      - server-name: /v1/update-client
        uuid: eatl-2-0-1-op-s-bm-007
      - server-name: /v1/list-ltps-and-fcs
        uuid: eatl-2-0-1-op-s-bm-008
      - server-name: /v1/redirect-topology-change-information
        uuid: eatl-2-0-1-op-s-bm-009
      - server-name: /v1/update-operation-key
        uuid: eatl-2-0-1-op-s-bm-010
      - server-name: /v1/update-operation-client
        uuid: eatl-2-0-1-op-s-bm-011
      - server-name: /v1/bequeath-your-data-and-die
        uuid: eatl-2-0-1-op-s-im-000
      - server-name: /v1/start-application-in-generic-representation
        uuid: eatl-2-0-1-op-s-bs-000
      - server-name: /v1/inform-about-application
        uuid: eatl-2-0-1-op-s-bs-001
      - server-name: /v1/inform-about-application-in-generic-representation
        uuid: eatl-2-0-1-op-s-bs-002
      - server-name: /v1/inform-about-release-history
        uuid: eatl-2-0-1-op-s-bs-003
      - server-name: /v1/inform-about-release-history-in-generic-representation
        uuid: eatl-2-0-1-op-s-bs-004
      - service-name: /v1/regard-application
        uuid: eatl-2-0-1-op-s-is-001
      - service-name: /v1/disregard-application
        uuid: eatl-2-0-1-op-s-is-002
      - service-name: /v1/list-applications
        uuid: eatl-2-0-1-op-s-is-003
      - service-name: /v1/list-records
        uuid: eatl-2-0-1-op-s-is-005
      - service-name: /v1/list-records-of-flow
        uuid: eatl-2-0-1-op-s-is-006
      - service-name: /v1/list-records-of-unsuccessful
        uuid: eatl-2-0-1-op-s-is-007
    consequent-requests:
      - client-name: ExecutionAndTraceLog://v1/record-service-request
        uuid: eatl-2-0-1-op-c-bs-eatl-2-0-1-000
```
